# Generated by Django 5.2 on 2025-05-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_alter_proyecto_options_alter_proyecto_created_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="proyecto",
            name="image",
            field=models.ImageField(upload_to="proyectos", verbose_name="Imagen"),
        ),
    ]
