# Generated by Django 5.2 on 2025-05-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["created"],
                "verbose_name": "categoría",
                "verbose_name_plural": "categorías",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={
                "ordering": ["-created", "order"],
                "verbose_name": "entrada",
                "verbose_name_plural": "entradas",
            },
        ),
        migrations.AddField(
            model_name="post",
            name="order",
            field=models.SmallIntegerField(default=0, verbose_name="Orden"),
        ),
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                related_name="get_posts", to="blog.category", verbose_name="Categorías"
            ),
        ),
    ]
