# Generated by Django 5.2 on 2025-05-11 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_options_alter_post_options_post_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="order",
            field=models.SmallIntegerField(
                blank=True, default=0, null=True, verbose_name="Orden"
            ),
        ),
    ]
