# Generated by Django 5.2 on 2025-05-09 23:46

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("curriculum", "0002_alter_cv_options_cv_image_position_cv_texto_boton"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cv",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Contenido"),
        ),
    ]
